# Generated by Django 3.0.8 on 2020-09-16 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('status', models.IntegerField(choices=[(0, 'Unavailable'), (1, 'Available'), (2, 'Archive')])),
                ('quantity', models.IntegerField()),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='inventory-item/', verbose_name='InventoryItem Image')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InventoryItemLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField()),
                ('quantity', models.IntegerField()),
                ('log_type', models.CharField(choices=[('stock in', 'stock in'), ('stock out', 'stock out')], max_length=20)),
                ('remarks', models.CharField(max_length=100)),
                ('inventory_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.InventoryItem')),
                ('logged_by', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.UserProfile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
