# Generated by Django 3.0.8 on 2020-09-07 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='inventory-item/', verbose_name='InventoryItem Image'),
        ),
    ]
