# Generated by Django 3.0.8 on 2020-08-12 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField(default=0, max_length=10)),
                ('description', models.TextField()),
                ('status', models.IntegerField(choices=[(0, 'Unavailable'), (1, 'Available')])),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
