# Generated by Django 3.0.8 on 2020-09-06 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20200830_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.IntegerField(choices=[(0, 'Unavailable'), (1, 'Available'), (2, 'Archive')]),
        ),
    ]
