# Generated by Django 3.0.8 on 2020-09-16 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('product', '0004_auto_20200906_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='inventoryItem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.InventoryItem'),
        ),
    ]
