# Generated by Django 3.0.8 on 2020-07-26 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertype',
            name='type',
            field=models.CharField(choices=[('Admin', 'Admin'), ('KitchenDevice', 'KitchenDevice'), ('CashierDevice', 'CashierDevice'), ('RestaurantDevice', 'RestaurantDevice')], default='Admin', max_length=50),
        ),
    ]
