# Generated by Django 3.0.8 on 2020-07-26 10:43

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200726_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='extra_info',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
    ]
