# Generated by Django 3.0.8 on 2020-07-28 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20200726_1043'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='type',
            new_name='user_type',
        ),
        migrations.RemoveField(
            model_name='usertype',
            name='type',
        ),
        migrations.AddField(
            model_name='usertype',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
