# Generated by Django 3.0.8 on 2020-07-28 10:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20200728_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='api_key',
            field=models.CharField(default=uuid.uuid4, max_length=255),
        ),
    ]
