# Generated by Django 3.0.8 on 2020-07-28 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20200728_1031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='api_key',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='extra_info',
        ),
    ]
